---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: registerappdeployment
spec:
 replicas: 2
 strategy:
    type: RollingUpdate
 selector:
   matchLabels:
     app: registerapp
 template:
  metadata:
   name: registerapppod
   labels:
     app: registerapp
  spec:
    containers:
    - name: registerappcontainer
      image: nandhanab/register-app
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: registerappsvc
spec:
  type: LoadBalancer
  selector:
   app: registerapp
  ports:
   - port: 80
     targetPort: 8080
...
