---
apiVersion: v1
kind: Deployment
metadata:
  name: Register-app-deploy
spec:
  selector:
    matchLabels:
        app: register-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  template:
    metadata:
      labels:
        app: register-app
    spec:
     containers:
      - name: register-app-container
        image: nandhanab/register-app
        imagePullPolicy: Always
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: Register-app-service
  labels:
    app: register-app
spec:
  selector:
    app: register-app
  type: LoadBalancer
  ports:
   - port: 8080
     targetPort: 80
...
