---
- name: Deploying Application to Kubernetes
  hosts: minikube
  gather_facts: true
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: registerappns
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        name: "{{ namespace_name }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        state: present
        src: /root/deployment.yml
        namespace: "{{ namespace_name }}"
...

