---
- hosts: all
  become: true
  tasks:
   - name: COPY DEPLOYMENT FILE TO KUBERNETES CLUSTER
     copy:
      src: deployment.yml
      dest: /root/
     
   - name: DELETE PREVIOUS KUBERNETES OBJECTS
     command: kubectl delete pod registerapppod
     command: kubectl delete svc registerappsvc
     command: kubectl delete deployment registerappdeployment

   - name: CREATE A DEPLOYMENT
     command: kubectl apply -f /root/deployment.yml
...
