---
- hosts: all
  become: true

  tasks:
    - name : DELETE OLD DEPLOYMENT
      command: kubectl delete -f  /opt/deloyment.yml

    - name: CREATE A DEPLOYMENT
      command: kubectl apply -f /opt/deployment.yml

...
